apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mysql.persistentvolume.name }}
  labels:
    app: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mysql.persistentvolume.size }}
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/Users/bernardogza/storage"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.mysql.persistentvolumeclaim.name }}
  labels:
    app: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: {{.Values.mysql.persistentvolumeclaim.size }}
