# This secret corresponds to the following values :
# username = mysql

apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  labels:
    app: wordpress
type: Opaque
data:
  username: YmVybmFyZG9fZ3ph
  password: YmU5MTE1MjlnYQ==

