kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-pv
  labels:
    app: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Mi

